### ISSUE TITLE
Not showing all sessions in Bldg Data report

### ISSUE THREAD

**Issue by krugerd** [MattWade-MS/QER#14]
I am trying to build and export a report showing all users who used Teams in a buildng on a particular subnet on a certain day, incoming or outgoing.  However after trying various ways the Bldg Data report is only showing me users with sessions received, not sessions initiated.

For example I can filter to the day with a First UPN, second UPN, and Organizer UPN to see usernames and session data but I only see calls received by those users in that building, I dont see their P2P or Conf calls they started with others. I know thise calls are in CQD as I can search and find them on other reports (tabs) and I can see the multiple in and out calls in the Call Analytics page of the Teams Admin Center.

I have an uploaded Building Location file and it appears to show me all the inside subnets in the default view which is great.  But when I try to add filters to the visual to also see user activity on those subnets it only seems to show me received.  

I've also tried the "User List" tab of the "Teams Utilization Report" PBI report as it seems to be able to provide something we need, but after trying a number of filters and visualizations, I am finding I cannot display all Teams activity (inbound or outbound).  I have got to the point where I have all Outgoing calls in one, and all Incoming calls in another, but not both.  (and not confs as well, just P2P)  

Here are my filters I'm using that seem to show all incoming calls to the building subnet (I think)
![in](https://user-images.githubusercontent.com/99920431/182260409-9a154565-6265-4e6f-aeb3-8722aa7f424b.JPG)

And here are the filters I'm using to show all outgoing calls from the building subnet (I think)
![out](https://user-images.githubusercontent.com/99920431/182260419-6ac350bf-f623-45ec-8c37-2b699a2b6da9.JPG)

I'm not sure how to combine them? and make sure I have included all P2P and CONF activity?

Is there a better way to do this?  Or am I just missing something?
Thanks

**Comment by krugerd** [comment]
I've also tried the "User List" tab of the "Teams Utilization Report" as it seems to be able to provide something we need, but when I add First Building Name and Second Building Name columns it doesn't show any data.  It does show results for First Subnet and Second Subnet.

**Comment by MattWade-MS** [comment]
Do not combine First and Second dimensions unless you are very comfortable with the concept.  I would also remove First and Second UPN from your query, it's not needed if you are just after a count.

Focus your report on Second endpoints only and limit to meetings (Session type = conf).

To make this a bit easier, I might suggest using a report already created.  Since this seems like a usage based report I would take say the ISP Usage visual.  Change the Y-axis dimension to Second Building Name and remove the Second ASN blank filter.  This will get you a visual showing the usage of buildings.

In a meeting, the first endpoint data will always be Microsoft.

In a p2p call, the first and second endpoint data is driven by the client.  You'll need TWO reports for this, one for First and one for Second.  Set your session type filter to P2P for each report as you cannot combine First and Second dimensions together for this type of report.

**Comment by krugerd** [comment]
Thanks for the reply Matt.  Some comments:
- re: "Focus your report on Second endpoints only and limit to meetings (Session type = conf)" will not work for us, as we need a report showing all activity inside buildings.  Not just CONF calls...
- the reason I wanted to include First UPN and Second UPN is to validate against what I know is happening in building, to compare the results of the report to the results I expect from users I know who are in buildings making a P2P call, receiving a P2P call, and joining a CONF call.  They show up as First or Second depending on the call type as you mention.
- I did start with an existing visualization (off the Bldg Data page) - the existing visualizations (Inside/Outside Ratio and Inside/Outside Pair Ratio I don't believe are capturing all this activity are they?  For example, it is filtering out Client:Client (just Client:Server), and the InsideCorp field does not seem to include Outside:Inside (just Inside:Outside).  
- The Inside/Outside Corp visual (top right) is really only showing Second Inside Corp (not First Inside Corp) so iI don't believe it shows the calls where the building is identified in First Building/First UPN.  (A call from a user in a building to a work from home user)  so this is why I attempted to create my own to make sure I'm capturing everything.
- I did manage to come up with the following, which seems to show all calls (Inside:Inside, Inside:Outside, and Outside:Inside, but NOT Outside:Outside).  But then I run into the problem of having duplicate rows and users showing up as both in First Building and Second Building (which might actually be the same building).  I have thought I could take this out to Excel and run some VBA on it to trim it and figure it out, but it seems like extra steps.  I really just want a count of users in buildings, and I'm missing something. 
![image](https://user-images.githubusercontent.com/99920431/183991607-ddc331d4-d862-47ed-92dc-9a5932a8351b.png)

**Comment by MattWade-MS** [comment]
I'll start with the last question first.  For this visual you are building, you need a measure which you did not include.  The query will not return the correct results until you add a measure such as Total Call Count or Total Stream Count.  You most likely have duplicate rows because you have P2P and CONF in the same visual.  Please break these up into two visuals.  For meetings only include Second dimensions.  For P2P you can include both but make sure to add the session type filter.  The reports are also built/queried by the dimension order.  So in this case, First UPN has priority 1, second UPN 2, and so on.  I recommend to start with the big dimension first (reverse your ordering).  There is also a better inside dimension you can use called Inside Corp Pair that will take the place of the First and Second Inside Corp dimension. 

Additionally, unless you are looking at PSTN data there is no caller/callee here.  In order to determine who "called" if this is important you need to leverage the First is Caller dimension for the P2P reports.  In VOIP land, both endpoints "call" each other and CQD is not concerned with who placed the call.

**Comment by krugerd** [comment]
Thanks for this Matt!
I did have Inside Corp Pair and First Is Caller previously included (among other things), but the report got messed up (as shown in my other open issue here.  I will work on adding a measure as you indicate.)
However, this report is now accurate in terms of users making calls - any kind, P2P or Conf, so I'm making some progress.  
But I've noticed I just added columns (and now the report is still not garbled which is great), but it is showing me this:
![image](https://user-images.githubusercontent.com/99920431/183996037-30981365-c9cc-4a49-9c7a-b953ea2f4761.png)
Shouldn't the Inside Corp Pair match the First Inside Corp and Second Inside Corp?  This was one of my concerns above, "Inside Corp Pair" doesn't include Outside:Inside, so all these calls (Outside to Inside) would be filtered out in this report if I just used that no?

**Comment by krugerd** [comment]
FYI, the display was OK with seven columns, but when I added "Session Type" the columns displayed the wrong data again, similar to my other issue.  (First UPN and Session Type rows were displayed in the opposite columns of where they should have been)

**Comment by krugerd** [comment]
I think the "garbled" or mixed up columns is happening when I add a field (measure/dimension) to the columns area, if I already have a filter set for the field (measure/dimension).  Session Type is a filter on all pages, and when I added that as a column, it messed up a couple columns.  Yet I can add Stream Direction, Total Stream Count, First User Count, etc. and the columns dont get messed up.

**Comment by krugerd** [comment]
I am now fairly confident I can do all this with one Power BI report – show Inside:Inside, Inside:Outside and Outside:Inside (and NOT Outside:Outside) for P2P and CONF calls.  (I really don’t want to create separate reports unless absolutely necessary).

So I end up exporting (ALL) the data from the Power BI report into excel, where I have created a VBA script to eliminate duplicates, and create a pivot table of Buildings and Users with a count of users per building, and user names to verify we didn’t miss any P2P or CONF calls.

This is perfect – BUT

The 10000 row limitation is a problem.  Currently it works fine, but once more people return to buildings, I wont see all the data as I will go past the 10000 row limit.

Two options I can think of:  (unless you can help me with a better one)….
-	I could elminiate reporting on UPNs and just do a count if that would work (experimenting now).  I need to keep the UPNs now just to verify the report is doing what I think it should be doing, and not missing anything.  I think its good now.
-	If I could figure out how to reduce the multiple entries in the report to just 1, this would help.  I don’t really care what the Media Type or Stream direction is, but Power BI shows me an entry for each one for each user.  If I could just get ONE entry for the multiple records, that would be ideal as it would eliminate a ton of rows I don’t need when I export and I would be set.

**Comment by krugerd** [comment]
I have a support case open with Microsoft on this and will comment thru that case.  Thanks Matt

**Comment by krugerd** [comment]
custom usage report is not supported.
